# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Dataset summary
df.info()

# Descriptive statistics for numerical features
df.describe()

# Checking for missing values
df.isnull().sum()

# Correlation heatmap
import seaborn as sns
import matplotlib.pyplot as plt

# Generate correlation matrix
corr_matrix = df.corr()

# Plotting correlation heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Matrix - California Housing Dataset')
plt.show()