# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Import necessary libraries
import pandas as pd
from sklearn.datasets import fetch_california_housing

# Load the California Housing dataset
data = fetch_california_housing()

# Convert to DataFrame for easier exploration
df = pd.DataFrame(data.data, columns=data.feature_names)

# Add target column to DataFrame
df['Price'] = data.target

# View the first few rows of the dataset
df.head()